export const galleryData = [
  {
    id: 1,
    title: "Natural Base",
    slug: "natural-base",
    category: "Natural Base",
    tag: "Skin prep",
    displayName: "Natural Base",
    image16x9: "/gallery/16x9/01-natural-base.jpg",
    image9x16: "/gallery/9x16/01-natural-base.jpg",
    altText: "Natural Base bridal look by Brides of Nilambary",
    sortOrder: 1,
    featured: true,
  },
  {
    id: 2,
    title: "Makeup Process",
    slug: "makeup-process",
    category: "Makeup Process",
    tag: "Professional brush detail",
    displayName: "Makeup Process",
    image16x9: "/gallery/16x9/02-makeup-process.jpg",
    image9x16: "/gallery/9x16/02-makeup-process.jpg",
    altText: "Makeup Process bridal look by Brides of Nilambary",
    sortOrder: 2,
    featured: true,
  },
  {
    id: 3,
    title: "Saree Draping",
    slug: "saree-draping",
    category: "Saree Styling",
    tag: "Pleat and fabric architecture",
    displayName: "Saree Draping",
    image16x9: "/gallery/16x9/03-saree-draping.jpg",
    image9x16: "/gallery/9x16/03-saree-draping.jpg",
    altText: "Saree Draping bridal look by Brides of Nilambary",
    sortOrder: 3,
    featured: false,
  },
  {
    id: 4,
    title: "Bridal Hairstyling",
    slug: "bridal-hairstyling-gajra",
    category: "Bridal Hairstyling",
    tag: "Gajra and hair accessory finish",
    displayName: "Bridal Hairstyling",
    image16x9: "/gallery/16x9/04-bridal-hairstyling-gajra.jpg",
    image9x16: "/gallery/9x16/04-bridal-hairstyling-gajra.jpg",
    altText: "Bridal Hairstyling bridal look by Brides of Nilambary",
    sortOrder: 4,
    featured: true,
  },
  {
    id: 5,
    title: "Hair Accessory Detail",
    slug: "hair-accessory-detail",
    category: "Bridal Hairstyling",
    tag: "Crystal vine detail",
    displayName: "Hair Accessory Detail",
    image16x9: "/gallery/16x9/05-hair-accessory-detail.jpg",
    image9x16: "/gallery/9x16/05-hair-accessory-detail.jpg",
    altText: "Hair Accessory Detail bridal look by Brides of Nilambary",
    sortOrder: 5,
    featured: false,
  },
  {
    id: 6,
    title: "Eye Detail",
    slug: "eye-detail",
    category: "Eye Details",
    tag: "Soft sculpt",
    displayName: "Eye Detail",
    image16x9: "/gallery/16x9/06-eye-detail.jpg",
    image9x16: "/gallery/9x16/06-eye-detail.jpg",
    altText: "Eye Detail bridal look by Brides of Nilambary",
    sortOrder: 6,
    featured: false,
  },
  {
    id: 7,
    title: "Full Bridal Transformation",
    slug: "bridal-transformation",
    category: "Final Look",
    tag: "Complete look",
    displayName: "Full Bridal Transformation",
    image16x9: "/gallery/16x9/07-bridal-transformation.jpg",
    image9x16: "/gallery/9x16/07-bridal-transformation.jpg",
    altText: "Full Bridal Transformation bridal look by Brides of Nilambary",
    sortOrder: 7,
    featured: true,
  },
  {
    id: 8,
    title: "Maharashtrian Bridal",
    slug: "maharashtrian-bridal",
    category: "Maharashtrian Bridal",
    tag: "Royal red ceremony",
    displayName: "Maharashtrian Bridal",
    image16x9: "/gallery/16x9/08-maharashtrian-bridal.jpg",
    image9x16: "/gallery/9x16/08-maharashtrian-bridal.jpg",
    altText: "Maharashtrian Bridal bridal look by Brides of Nilambary",
    sortOrder: 8,
    featured: true,
  },
  {
    id: 9,
    title: "Final Look",
    slug: "final-look",
    category: "Final Look",
    tag: "Signature finish",
    displayName: "Final Look",
    image16x9: "/gallery/16x9/09-final-look.jpg",
    image9x16: "/gallery/9x16/09-final-look.jpg",
    altText: "Final Look bridal look by Brides of Nilambary",
    sortOrder: 9,
    featured: true,
  },
  {
    id: 10,
    title: "Temple Gold Styling",
    slug: "gold-saree-smile",
    category: "Saree Styling",
    tag: "Gold balance",
    displayName: "Temple Gold Styling",
    image16x9: "/gallery/16x9/10-gold-saree-smile.jpg",
    image9x16: "/gallery/9x16/10-gold-saree-smile.jpg",
    altText: "Temple Gold Styling bridal look by Brides of Nilambary",
    sortOrder: 10,
    featured: false,
  },
  {
    id: 11,
    title: "Reception Glow",
    slug: "gold-saree-front",
    category: "Final Look",
    tag: "Golden bridal smile",
    displayName: "Reception Glow",
    image16x9: "/gallery/16x9/11-gold-saree-front.jpg",
    image9x16: "/gallery/9x16/11-gold-saree-front.jpg",
    altText: "Reception Glow bridal look by Brides of Nilambary",
    sortOrder: 11,
    featured: false,
  },
  {
    id: 12,
    title: "Side Profile Bridal",
    slug: "side-profile-bridal",
    category: "Portrait",
    tag: "Profile glow",
    displayName: "Side Profile Bridal",
    image16x9: "/gallery/16x9/12-side-profile-bridal.jpg",
    image9x16: "/gallery/9x16/12-side-profile-bridal.jpg",
    altText: "Side Profile Bridal bridal look by Brides of Nilambary",
    sortOrder: 12,
    featured: false,
  },
  {
    id: 13,
    title: "Jewellery Styling",
    slug: "jewellery-detail",
    category: "Jewellery",
    tag: "Necklace and ornament detail",
    displayName: "Jewellery Styling",
    image16x9: "/gallery/16x9/13-jewellery-detail.jpg",
    image9x16: "/gallery/9x16/13-jewellery-detail.jpg",
    altText: "Jewellery Styling bridal look by Brides of Nilambary",
    sortOrder: 13,
    featured: false,
  },
  {
    id: 14,
    title: "Soft Rose Eye Detail",
    slug: "eyes-closed-detail",
    category: "Eye Details",
    tag: "Eyes closed finish",
    displayName: "Soft Rose Eye Detail",
    image16x9: "/gallery/16x9/14-eyes-closed-detail.jpg",
    image9x16: "/gallery/9x16/14-eyes-closed-detail.jpg",
    altText: "Soft Rose Eye Detail bridal look by Brides of Nilambary",
    sortOrder: 14,
    featured: false,
  },
] as const;
